import { Server, Socket } from "socket.io";
import { addMember } from "../../../lib/room";
import { getRoomModerationState } from "../../../lib/moderation";

type JoinRoomPayload = {
  roomId: string;
  user: {
    id: string;
    name: string;
  };
};

type JoinRoomResponse = {
  success: boolean;
  message?: string;
  code?: string;
};

export const handleJoinRoom = async (
  io: Server,
  socket: Socket,
  { roomId, user }: JoinRoomPayload,
): Promise<JoinRoomResponse> => {
  try {
    console.log(`[Socket] ${user.id} joining realtime room ${roomId}`);

    // Prevent duplicate Socket.IO joining.
    if (socket.data.roomId === roomId && socket.rooms.has(roomId)) {
      return {
        success: true,
        message: "Already joined room",
      };
    }

    /**
     * Atomically validate and add the member.
     *
     * addMember() handles:
     * - room exists
     * - room ended
     * - duplicate member
     * - room capacity
     * - adding member
     */
    const memberResult = await addMember({
      roomId,
      member: {
        id: user.id,
        name: user.name,
      },
    });

    
    // Get participants BEFORE adding this socket to the Socket.IO room.
    const existingSockets = await io.in(roomId).fetchSockets();

    const existingUsers = existingSockets
      .filter((existingSocket) => existingSocket.id !== socket.id)
      .map((existingSocket) => ({
        user: {
          id: existingSocket.data.userId,
          name: existingSocket.data.userName,
        },
        socketId: existingSocket.id,
      }))
      .filter((item) => item.user.id);

    await socket.join(roomId);

    await socket.join(`user:${user.id}`);

    socket.data.roomId = roomId;
    socket.data.userId = user.id;
    socket.data.userName = user.name;
    socket.data.socketId = socket.id;

    const moderationState = await getRoomModerationState(roomId);
    io.to(roomId).emit("room-moderator-state", {
      roomId,
      moderatorIds: moderationState.moderatorIds,
      kickedMemberIds: moderationState.kickedMemberIds,
    });

    // Send initial state to the joining user.

    socket.emit("room-force-muted-state", {
      roomId,
      ...moderationState,
    });

    socket.emit("room-participants", {
      roomId,
      participants: existingUsers,
    });

    
    // Notify existing realtime participants.
    socket.to(roomId).emit("user-joined", {
      roomId,
      user: {
        id: user.id,
        name: user.name,
      },
      socketId: socket.id,
    });

    /**
     * Notify room-list / room-details listeners.
     *
     * Only emit this if this was a newly added member.
     */
    if (memberResult.added) {
      io.emit("joinedMember", {
        roomId,
        newMember: {
          id: user.id,
          name: user.name,
        },
      });
    }

    console.log(`[Socket] ${user.id} successfully joined ${roomId}`);

    return {
      success: true,
      message: memberResult.alreadyMember
        ? "Rejoined room successfully"
        : "Joined room successfully",
    };
  } catch (error) {
    console.error("[Socket] Failed to join room:", error);

    /**
     * The error is already generated by addMember()
     * for cases such as:
     *
     * - Room not found
     * - Room ended
     * - Room full
     */
    const message =
      error instanceof Error ? error.message : "Failed to join room";

    return {
      success: false,
      message,
      code: message.includes("removed from this room")
        ? "MEMBER_KICKED"
        : undefined,
    };
  }
};
